# Generated by Django 4.2.7 on 2024-05-08 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='middle_name',
            field=models.CharField(default=' ', max_length=30),
        ),
    ]
