# Generated by Django 4.2.7 on 2024-05-08 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_user_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
    ]
