# Generated by Django 4.2.7 on 2024-05-08 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_user_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
    ]
