# Generated by Django 4.2.7 on 2024-05-10 04:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_remove_user_education_user_educations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='year_of_experience',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation', models.CharField(max_length=100)),
                ('top_skills', models.CharField(max_length=100)),
                ('still_work', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='NA', max_length=3)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_workexperience', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='workexperience',
            field=models.ManyToManyField(related_name='workexusers', to='account.workexperience'),
        ),
    ]
