# Generated by Django 4.2.7 on 2024-05-10 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_alter_user_year_of_experience_workexperience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='month_of_experience',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
