# Generated by Django 4.2.7 on 2024-05-11 13:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_rename_end_date_education_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexperience',
            name='end',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
