# Generated by Django 4.2.7 on 2024-05-11 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_alter_workexperience_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(default='null', max_length=200),
        ),
    ]
