# Generated by Django 4.2.7 on 2024-05-12 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_user_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='workexperience',
            name='jobPost',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
