# Generated by Django 4.2.7 on 2024-05-13 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_workexperience_jobpost_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='education',
            name='school',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='education',
            name='specialisation',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='firstName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='lastName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.CharField(default='null', max_length=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='middleName',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='skill',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='jobPost',
            field=models.CharField(default='null', max_length=500),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='organisation',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='topSkill',
            field=models.CharField(max_length=500),
        ),
    ]
