# Generated by Django 4.2.7 on 2024-05-13 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_alter_education_degree_alter_education_school_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='middleName',
            field=models.CharField(max_length=100),
        ),
    ]
