# Generated by Django 4.2.7 on 2024-05-13 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_alter_user_middlename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='middleName',
            field=models.CharField(default='', max_length=100),
        ),
    ]
